//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPSNotebook.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GPSNotebook.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на confirm password.
        /// </summary>
        internal static string ConfirmPasswordPlaceholder {
            get {
                return ResourceManager.GetString("ConfirmPasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Passwords are different.
        /// </summary>
        internal static string DifferentPasswordError {
            get {
                return ResourceManager.GetString("DifferentPasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на GPSNotebook.
        /// </summary>
        internal static string HomePageTitle {
            get {
                return ResourceManager.GetString("HomePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Wrong Mail!.
        /// </summary>
        internal static string InvalidMailMessage {
            get {
                return ResourceManager.GetString("InvalidMailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid Mail.
        /// </summary>
        internal static string InvalidMailTitle {
            get {
                return ResourceManager.GetString("InvalidMailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Weak password!.
        /// </summary>
        internal static string InvalidPasswordMessage {
            get {
                return ResourceManager.GetString("InvalidPasswordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid Password.
        /// </summary>
        internal static string InvalidPasswordTitle {
            get {
                return ResourceManager.GetString("InvalidPasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Log Out.
        /// </summary>
        internal static string LogOutText {
            get {
                return ResourceManager.GetString("LogOutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на e-mail.
        /// </summary>
        internal static string MailPlaceholder {
            get {
                return ResourceManager.GetString("MailPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Map.
        /// </summary>
        internal static string MapTabTitle {
            get {
                return ResourceManager.GetString("MapTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на name.
        /// </summary>
        internal static string NamePlaceholder {
            get {
                return ResourceManager.GetString("NamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ok.
        /// </summary>
        internal static string OkText {
            get {
                return ResourceManager.GetString("OkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на password.
        /// </summary>
        internal static string PasswordPlaceholder {
            get {
                return ResourceManager.GetString("PasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Pins.
        /// </summary>
        internal static string PinsListTabTitle {
            get {
                return ResourceManager.GetString("PinsListTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Such User already exists.
        /// </summary>
        internal static string RegisterFailedMessage {
            get {
                return ResourceManager.GetString("RegisterFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Register failed.
        /// </summary>
        internal static string RegisterFailedTitle {
            get {
                return ResourceManager.GetString("RegisterFailedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sign In.
        /// </summary>
        internal static string SignInButton {
            get {
                return ResourceManager.GetString("SignInButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Wrong email or password.
        /// </summary>
        internal static string SignInErrorMessage {
            get {
                return ResourceManager.GetString("SignInErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sign In error!.
        /// </summary>
        internal static string SignInErrorTitle {
            get {
                return ResourceManager.GetString("SignInErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Users Sign In.
        /// </summary>
        internal static string SignInTitle {
            get {
                return ResourceManager.GetString("SignInTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sign up.
        /// </summary>
        internal static string SignUpButton {
            get {
                return ResourceManager.GetString("SignUpButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SIGN UP.
        /// </summary>
        internal static string SignUpLink {
            get {
                return ResourceManager.GetString("SignUpLink", resourceCulture);
            }
        }
        
        internal static string SignUpTitle {
            get {
                return ResourceManager.GetString("SignUpTitle", resourceCulture);
            }
        }
    }
}
